# **Problem Statement :** Arjun, Darsh and Harsha are planning to go for a few day's trips. They need to know the budget for different numbers of days. For example, they want to go to OOTY for 3 days. Develop an ML algorithm to help find the best budget trip based on the distance (kilometer) and the number of days using the DataScience.

# **Understanding the Business and Client requirement**
###The client wants to predict  the total amount of the trip based on trip distance and total number of trip days.

# **Data Collection**
###  Dataset used is our own dataset

In [27]:
# importing pandas library and converting the csv file into dataframe
import pandas as pd
df = pd.read_csv('tripdata.csv')
df

   distance (in km)  days  budget
0                95     2    3000
1               110     3    3800
2               135     5    6000
3               140     2    5000
4               115     3    4000
5               126     4    4700
6               132     3    5200
7               100     3    3200
8               109     4    3500

# **Data Analysis**

In [8]:
#checking if there is a null value or not
df.isnull()

   distance (in km)   days  budget
0             False  False   False
1             False  False   False
2             False  False   False
3             False  False   False
4             False  False   False
5             False  False   False
6             False  False   False
7             False  False   False
8             False  False   False

In [9]:
df.isnull().count()

distance (in km)    9
days                9
budget              9
dtype: int64

# **Preparing X and y**

In [11]:
#Dropping budget column as we need distance and days to predict the budget(y - dependent variable)
X = df.drop(['budget'], axis = 1)
X

   distance (in km)  days
0                95     2
1               110     3
2               135     5
3               140     2
4               115     3
5               126     4
6               132     3
7               100     3
8               109     4

In [12]:
#Assigning budget column to y variable
y = df['budget']
y

0    3000
1    3800
2    6000
3    5000
4    4000
5    4700
6    5200
7    3200
8    3500
Name: budget, dtype: int64

# **Developing the ML Model**

In [13]:
#importing the library
from sklearn import linear_model

In [16]:
#creating a reference object to linear_model
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [18]:
#fit the data
reg.fit(X,y)

LinearRegression()

In [28]:
# predicting the output
reg.predict(X)

array([2696.05193429, 3767.83253842, 5632.11446741, 5209.5654478 ,
       4047.1118177 , 4895.46899841, 4996.66136725, 3209.27397986,
       3945.91944886])

In [20]:
#accuracy
reg.score(X,y)

0.932678707045388

In [21]:
reg.coef_

array([ 55.85585586, 233.9427663 ])

In [22]:
reg.intercept_

-3078.1399046104943

In [23]:
km = int(input("Enter the distance: "))
days = int(input("Enter the number of days you're going to stay: "))
price = reg.predict([[km,days]])
print("You will need",price, "for the trip")

Enter the distance: 200
Enter the number of days you're going to stay: 6
You will need [9496.68786433] for the trip

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

In [24]:
#downloading the model
import pickle
with open('budgetmodel', 'wb') as f:
  pickle.dump(reg, f)