# **Problem Statement :** 
### Arjun, Darsh and Harsha are planning to go for a few day's trips. They need to know the budget for different numbers of days. For example, they want to go to OOTY for 3 days. Develop an ML algorithm to help find the best budget trip based on the distance (kilometer) and the number of days using the DataScience.

# **Understanding the Business and Client requirement**
###The client wants to predict  the total amount of the trip based on trip distance and total number of trip days.

# **Data Collection**
###  Dataset used is our own dataset

In [16]:
# importing pandas library and converting the csv file into dataframe
import pandas as pd
df = pd.read_csv('tripdata.csv')
df

    distance (in km)  days  budget
0                 95     2    3000
1                110     3    3800
2                135     5    6000
3                140     2    5000
4                115     3    4000
5                126     4    4700
6                132     3    5200
7                100     3    3200
8                109     4    3500
9                229     5    4200
10               260     7    4500
11               320     6    5000
12               390     4    5200
13               450     8    6000
14               520    10    8000
15               575     8    8600
16               632    12   12000

# **Data Analysis**

In [17]:
#checking if there is a null value or not
df.isnull()

    distance (in km)   days  budget
0              False  False   False
1              False  False   False
2              False  False   False
3              False  False   False
4              False  False   False
5              False  False   False
6              False  False   False
7              False  False   False
8              False  False   False
9              False  False   False
10             False  False   False
11             False  False   False
12             False  False   False
13             False  False   False
14             False  False   False
15             False  False   False
16             False  False   False

In [18]:
df.isnull().count()

distance (in km)    17
days                17
budget              17
dtype: int64

# **Preparing X and y**

In [19]:
#Dropping budget column as we need distance and days to predict the budget(y - dependent variable)
X = df.drop(['budget'], axis = 1)
X

    distance (in km)  days
0                 95     2
1                110     3
2                135     5
3                140     2
4                115     3
5                126     4
6                132     3
7                100     3
8                109     4
9                229     5
10               260     7
11               320     6
12               390     4
13               450     8
14               520    10
15               575     8
16               632    12

In [20]:
#Assigning budget column to y variable
y = df['budget']
y

0      3000
1      3800
2      6000
3      5000
4      4000
5      4700
6      5200
7      3200
8      3500
9      4200
10     4500
11     5000
12     5200
13     6000
14     8000
15     8600
16    12000
Name: budget, dtype: int64

# **Developing the ML Model**

In [21]:
#importing the library
from sklearn import linear_model

In [22]:
#creating a reference object to linear_model
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [23]:
#fit the data
reg.fit(X,y)

LinearRegression()

In [24]:
# predicting the output
reg.predict(X)

array([3323.68105102, 3757.53916696, 4596.38846752, 3583.48343291,
       3786.40609828, 4197.17066916, 3884.55366477, 3699.80530431,
       4099.02310267, 5139.08677636, 6012.5763945 , 6011.72224838,
       5721.34464293, 7456.77710669, 8555.42878914, 8178.45038972,
       9896.56269469])

In [25]:
# predicting the output
km = int(input("Enter the distance: "))
days = int(input("Enter the number of days you're going to stay: "))
price = reg.predict([[km,days]])
a = price
print("You will need",a, "for the trip")

Enter the distance: 320
Enter the number of days you're going to stay: 5
You will need [5664.4649264] for the trip

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

In [26]:
#accuracy
reg.score(X,y)

0.7808918191260327

In [27]:
reg.coef_

array([  5.77338626, 347.25732198])

In [28]:
reg.intercept_

2080.6947119575416

In [29]:
#downloading the model
import pickle
with open('budgetmodel', 'wb') as f:
  pickle.dump(reg, f)